on: push
name: make test
jobs:
  maketest:
    name: make test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: make test
        run: make dtest
        shell: bash
